In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/sample_data/npr.csv')

In [3]:
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [5]:
df['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv = CountVectorizer(max_df=0.9,min_df=2,stop_words='english')

In [9]:
dtm = cv.fit_transform(df['Article'])

In [10]:
dtm

<12239x55898 sparse matrix of type '<class 'numpy.int64'>'
	with 3094384 stored elements in Compressed Sparse Row format>

In [11]:
from sklearn.decomposition import LatentDirichletAllocation

In [12]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [13]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [14]:
#Grabbing the vocabulary of words

In [15]:
len(cv.get_feature_names())

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


55898

In [16]:
import random

random_word_id = random.randint(0,55898)
cv.get_feature_names()[random_word_id]

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'ounces'

In [17]:
len(LDA.components_)

7

In [18]:
type(LDA.components_)

numpy.ndarray

In [20]:
LDA.components_

array([[8.13206719e+00, 3.01685351e+02, 1.42857150e-01, ...,
        1.42857148e-01, 6.14196189e+00, 1.42914799e-01],
       [3.89234255e+00, 9.99167961e+02, 1.42871911e-01, ...,
        1.43205620e-01, 1.42857143e-01, 1.43083135e-01],
       [1.43248487e-01, 1.13007830e+03, 1.42901340e-01, ...,
        1.42857152e-01, 1.42857144e-01, 1.42857149e-01],
       ...,
       [2.53815889e+00, 1.17882047e+03, 1.42857150e-01, ...,
        1.44680618e-01, 1.42857143e-01, 1.42887962e-01],
       [2.11014223e+01, 1.22210860e+03, 1.42857153e-01, ...,
        1.43467771e-01, 1.42857143e-01, 8.99124723e-01],
       [1.44469819e+01, 6.37587864e+02, 1.42857152e-01, ...,
        1.42857150e-01, 1.42857143e-01, 1.42910473e-01]])

In [21]:
single_topic = LDA.components_[0]

In [22]:
single_topic.argsort()

array([55889, 23606, 24341, ..., 38890, 43447, 51457])

In [23]:
import numpy as np

In [24]:
# arr = np.array([10,200,1])

In [25]:
# arr

array([ 10, 200,   1])

In [26]:
# arr.argsort()

array([2, 0, 1])

In [27]:
# ARGSORT --> INDEX POSITIONS SORTED FROM LEAST --> GREATEST
# TOP 10 VALUES (10 GREATEST VALUES)
# LAST 10 VALUES OF ARGSORT()
single_topic.argsort()[-10:] # grab the last 10 values of .argsort()

array([34115, 54670, 24172, 16445, 34892,  8074,  9979, 38890, 43447,
       51457])

In [30]:
top_twenty_words = single_topic.argsort()[-20:] 

In [31]:
for index in top_twenty_words:
  print(cv.get_feature_names()[index])

vote
just
presidential
political
voters
people
donald
party
republican
state
new
white
house
election
obama
campaign
clinton
president
said
trump


In [32]:
for index,topic in enumerate(LDA.components_):
  print(f"THE TOP 15 WORDS FOR TOPIC #{index}")
  print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
  print('\n')
  print('\n')

THE TOP 15 WORDS FOR TOPIC #0


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['people', 'donald', 'party', 'republican', 'state', 'new', 'white', 'house', 'election', 'obama', 'campaign', 'clinton', 'president', 'said', 'trump']




THE TOP 15 WORDS FOR TOPIC #1
['kids', 'percent', 'education', 'don', 'new', 'work', 'years', 'children', 'just', 'like', 'students', 'women', 'school', 'people', 'says']




THE TOP 15 WORDS FOR TOPIC #2
['year', 'percent', 'government', 'tax', 'states', 'president', 'insurance', 'law', 'state', 'federal', 'people', 'says', 'care', 'said', 'health']




THE TOP 15 WORDS FOR TOPIC #3
['world', 'don', 'years', 'life', 'music', 'really', 'way', 'think', 'know', 'new', 'time', 'says', 'people', 'just', 'like']




THE TOP 15 WORDS FOR TOPIC #4
['time', 'percent', 'disease', 'research', 'university', 'years', 'just', 'water', 'study', 'food', 'new', 'like', 'health', 'people', 'says']




THE TOP 15 WORDS FOR TOPIC #5
['attack', 'isis', 'syria', 'reports', 'international', 'years', 'city', 'country', 'government', 'military', 'world', '

In [33]:
dtm

<12239x55898 sparse matrix of type '<class 'numpy.int64'>'
	with 3094384 stored elements in Compressed Sparse Row format>

In [34]:
topic_results = LDA.transform(dtm)

In [37]:
topic_results[0].argmax()

0

In [39]:
df['Topic'] = topic_results.argmax(axis=1)

In [40]:
df

Article  Topic
0      In the Washington of 2016, even when the polic...      0
1        Donald Trump has used Twitter  —   his prefe...      0
2        Donald Trump is unabashedly praising Russian...      0
3      Updated at 2:50 p. m. ET, Russian President Vl...      0
4      From photography, illustration and video, to d...      6
...                                                  ...    ...
12234  The number of law enforcement officers shot an...      6
12235    Trump is busy these days with victory tours,...      0
12236  It’s always interesting for the Goats and Soda...      4
12237  The election of Donald Trump was a surprise to...      0
12238  Voters in the English city of Sunderland did s...      1

[12239 rows x 2 columns]